echo -ne "Uptime: "; uptime
# echo '==========================================================='
echo ''

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# bureau, smt, terminalparty, wezm, ys
ZSH_THEME="wezm"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=3

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras npm osx brew sudo z)

# binds hex 0x18 0x7f with deleting everything to the left of the cursor
# use it in iterm to bind cmd+backspace to send that hex code
bindkey "^X\\x7f" backward-kill-line

# Keypad Fix for iTerm2
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[On" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * / =
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
bindkey -s "^[OX" "="

# Persist the dirs stack across sessions. http://chneukirchen.org/blog/archive/2012/02/10-new-zsh-tricks-you-may-not-know.html
DIRSTACKSIZE=9
DIRSTACKFILE=~/.zdirs
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
	dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
	[[ -d $dirstack[1] ]] && cd $dirstack[1] && cd $OLDPWD
fi
chpwd() {
	print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
}


# export MANPATH="/usr/local/man:$MANPATH"

export PATH=/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/git/bin:$PATH

# Android dev
export PATH=$HOME/android-sdk/tools:$HOME/android-sdk/platform-tools:$PATH

# NPM and yarn
export PATH=./node_modules/.bin:$PATH
export PATH=$PATH:`yarn global bin`

# HOMEBREW
# This line replaces basic system commands with linux versions, which right now
# breaks some of my aliases like ls. Can still run them all with 'g' prefixed (gls etc.)
# export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

# X11
export PATH=/opt/X11/bin:$PATH
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig

# NVM - THIS NOW LIVES IN ZPROFILE
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# RVM - whines if it isn't the first entry in $PATH
# export PATH=$HOME/.rvm/gems/ruby-2.0.0-p247/bin:$HOME/.rvm/gems/ruby-2.0.0-p247@global/bin:$HOME/.rvm/rubies/ruby-2.0.0-p247/bin:$HOME/.rvm/bin:$PATH

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source $ZSH/oh-my-zsh.sh

[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion # NVM auto completion. Must load after sourcing oh-my-zsh.

# User configuration
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle :compinstall filename '/Users/justin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Prevent tabs from sharing history (http://apple.stackexchange.com/questions/75571/the-history-is-shared-between-my-iterm2-terminal-tabs-how-can-i-switch-that-off)
unsetopt inc_append_history
unsetopt share_history

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# figlet -f cyberlarge $user

# emulate zsh -c '. ~/.nvm/nvm.sh'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias lsx='ls -aplhfG'
alias lsr='ls -aplhGrc'
alias ll='ls -l'
alias up='cd ..'

alias gits='git status'
alias gs='git status'
alias gitd='git diff'
alias gitb='git branch'
alias gitl='git log --stat --relative-date --since=24.hours --graph'
alias gitll='git log --stat --relative-date -p'
alias gitl2='git log --graph --abbrev-commit --decorate --date=relative --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(black)%s%C(reset) %C(bold black)- %an%C(reset)%C(bold yellow)%d%C(reset)" --all'
alias gitp='git push'
alias gitf='git fetch'
alias gitc='git checkout'
alias gitbclean='git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d'
alias hosts='open -a Atom /etc/hosts'
alias npmls0='npm ls --depth=0'
